name: HealthStack Auth CI

on:
  push:
    paths:
      - "src/HealthStack.Auth/**"
      - "tests/HealthStack.Auth.UnitTests/**"
      - "tests/HealthStack.Auth.IntegrationTests/**"
    branches: ["master"]
  pull_request:
    paths:
      - "src/HealthStack.Auth/**"
      - "tests/HealthStack.Auth.UnitTests/**"
      - "tests/HealthStack.Auth.IntegrationTests/**"
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore HealthStack.sln

      # 4. Build solution
      - name: Build
        run: dotnet build HealthStack.sln --no-restore --configuration Release

      # 5. Run unit tests
      - name: Run unit tests
        run: dotnet test tests/HealthStack.Auth.UnitTests --no-build --configuration Release --logger "trx;LogFileName=unit-tests.trx"

      # 6. Run integration tests
      - name: Run integration tests
        run: dotnet test tests/HealthStack.Auth.IntegrationTests --no-build --configuration Release --logger "trx;LogFileName=integration-tests.trx"
